/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/YUshtuQ0bN8
 */
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Separator } from "@/components/ui/separator"

export function sign-in() {
  return (
    <div key="1" className="w-full space-y-6">
      <div className="flex flex-col min-h-screen">
        <div className="flex-1 flex flex-col justify-center py-6 space-y-6">
          <div className="space-y-2 text-center">
            <h1 className="text-3xl font-bold">Welcome</h1>
            <p className="text-gray-500 dark:text-gray-400">Enter your information to login or create an account</p>
          </div>
          <div className="mx-auto space-y-6 max-w-sm w-full">
            <div className="space-y-2">
              <Label htmlFor="email">Email</Label>
              <Input id="email" placeholder="m@example.com" type="email" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="password">Password</Label>
              <Input id="password" type="password" />
            </div>
            <Button className="w-full">Login</Button>
            <Separator />
            <div className="space-y-2">
              <Button className="w-full" variant="ghost">
                Create an account
              </Button>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
